if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

# show number of running tasks
PS1="\u@\h:\W [\j] \$ "

export CLICOLOR=1
# export LSCOLORS=GxFxCxDxBxegedabagaced
export PATH=/usr/local/bin:$PATH
export PATH=~/.cabal/bin:$PATH
export PROJECT_DIR="$HOME/www"
export EDITOR="vim"

# aliases
alias top="top -ocpu"
alias dcc="drush cc all"
alias wcc="wp cache flush && wp rewrite flush && wp transient delete-all"
alias tagsdrupal="ctags -R --langmap=php:+.engine.inc.module.theme --php-kinds=cdfi"
alias tagssymfony="ctags -R --languages=php --php-kinds=cif --exclude=.git/* --exclude=app/* --exclude=bin/* --exclude=web/* --exclude=tests/* --exclude=*/Test/* --exclude=*/Tests/* --exclude=*test* --exclude=*Form/Type* --exclude=vendor/*/vendor --exclude=composer.phar --fields=+aimS"
alias hosts="$EDITOR /etc/hosts"

# set-option -g mouse-select-pane on
# set-option -g mouse-select-window on
# set-option -g mouse-resize-pane on
# set-window-option -g mode-mouse on

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
export RBENV_ROOT=/usr/local/var/rbenv
export PATH=/usr/local/var/rbenv/shims:$PATH


# Swap the php version
# export PATH="$(brew --prefix homebrew/php/php54)/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

_www()
{
  local cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=( $(compgen -W "$(ls -1 $PROJECT_DIR)" -- $cur) )
}

function xipio () {
  local ip=`ifconfig en0 | egrep -o "inet [^ ]+" | cut -d ' ' -f 2-`
  open "http://$1.$ip.xip.io"
}
complete -F _www xipio

function www () {
  cd /Users/andrejs/www/"$1";
}
complete -F _www www

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Work
source ~/.bash_boozt
