set nocompatible

runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

syntax on
filetype plugin indent on

set number
set wrap
set noswapfile
set nobackup
set nowritebackup
set lazyredraw

set winheight=5
set winminheight=5

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set showmatch
set matchtime=1

set wildmenu

set path=**
nnoremap <leader>f :find *

set incsearch
set hlsearch
set ignorecase
set smartcase

set hidden

set laststatus=2

set cursorline
set scrolloff=5

set pastetoggle=<F2>
nnoremap <F3> :NERDTreeToggle<CR>
nnoremap <F5> :GundoToggle<CR>
nnoremap <F6> :TagbarToggle<CR>
nnoremap <leader>l :ls<cr>:b<space>
nnoremap <leader>r :source ~/.vimrc<CR>
nnoremap <leader>c :ccl<CR>
nnoremap <leader>a :Ag<space>""<left>
nnoremap <leader>dc :!drush cc all<CR>
cnoremap <expr> %% expand('%:h').'/'

nnoremap <silent> <C-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <C-j> :TmuxNavigateDown<cr><C-W>_
nnoremap <silent> <C-k> :TmuxNavigateUp<cr><C-W>_
nnoremap <silent> <C-l> :TmuxNavigateRight<cr>
nnoremap <silent> <C-\> :TmuxNavigatePrevious<cr>

" search for tags up to home directory
set tags+=tags;~

" set ttyfast

set showcmd

set ruler

set list
set listchars=tab:>-,trail:·

set backspace=indent,eol,start

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

set mouse=a

set clipboard=unnamed

" enables split resizing with mouse
if &term =~ '^screen'
  " tmux knows the extended mouse mode
  set ttymouse=xterm2
endif

inoremap <F1> <nop>
nnoremap <F1> <nop>
vnoremap <F1> <nop>

" Save as sudo
cmap w!! w !sudo tee > /dev/null %

let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_php_checkers=['php']
let g:syntastic_scss_checkers = ['scss_lint']

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  "set grepprg=ag\ --nogroup\ --nocolor
endif

let g:ag_prg = 'ag --nogroup --column --depth -1 --ignore node_modules --ignore sql --ignore schema'

set t_Co=256
set background=dark

"let g:hybrid_use_iTerm_colors = 1
colorscheme hybrid

let g:vimwiki_list = [{'path': '~/Dropbox/notes/', 'ext': '.txt'}]
let g:vimwiki_global_ext = 0
